apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deny-all-ingress.yaml
  - allow-dns.yaml
  - allow-same-namespace.yaml
  - allow-monitoring.yaml
  - allow-ingress-controller.yaml
  - allow-external-egress.yaml
  - allow-cloudflare-tunnel.yaml