apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fusionauth
  labels:
    app.kubernetes.io/name: fusionauth
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: caicedo-seguros
    caicedo.seguros/tier: application
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fusionauth
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /api/status
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace