apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  labels:
    app.kubernetes.io/name: backup-storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: data-management
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi