apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmaps.yaml
  - backup-pvc.yaml
  - backup-cronjob-template.yaml
  - migration-job-template.yaml
  - db-maintenance-cronjob.yaml
  - cleanup-cronjob.yaml
  - network-policies.yaml

labels:
  - pairs:
      conecta.seguros/managed-by: platform-team