apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

resources:
  - ../../base/platform/namespaces/develop
  - ../../components/postgresql
  - ../../components/fusionauth

replicas:
  - name: fusionauth
    count: 1
  - name: postgresql
    count: 1

images:
  - name: fusionauth/fusionauth-app
    newTag: "1.62.1"
  - name: postgres
    newTag: "18"