apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

labels:
  - pairs:
      app: postgresql
      managed-by: kustomize
    includeSelectors: true

resources:
  - statefulset.yaml

images:
  - name: postgres
    newTag: "18"