apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ingress
  - certificate-policy.yaml

labels:
  - pairs:
      caicedo.seguros/environment: production

# Note: Production Ingress files must use the annotation:
#   cert-manager.io/cluster-issuer: letsencrypt-production