apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - storage
  - security
  - scheduling
  - namespace-scoped/rbac/clusterroles.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: caicedo-seguros
      caicedo.seguros/managed-by: platform-team
    includeSelectors: false