apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusionauth
  labels:
    app.kubernetes.io/name: fusionauth
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway-service
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eureka-server
  labels:
    app.kubernetes.io/name: eureka-server
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-default
  labels:
    app.kubernetes.io/name: microservice-default
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    caicedo.seguros/tier: data
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
  labels:
    app.kubernetes.io/name: job-runner
    caicedo.seguros/tier: infrastructure
automountServiceAccountToken: false