apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: develop

labels:
  - pairs:
      caicedo.seguros/environment: develop

patches:
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
      - op: replace
        path: /spec/template/spec/initContainers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 5Gi
      - op: add
        path: /spec/template/spec/priorityClassName
        value: data-critical