apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: promtail
  ports:
    - name: http-metrics
      port: 3101
      targetPort: http-metrics
      protocol: TCP