apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fusionauth-reader
  labels:
    app.kubernetes.io/name: fusionauth-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: platform
subjects:
  - kind: ServiceAccount
    name: fusionauth
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-discovery
  labels:
    app.kubernetes.io/name: gateway-discovery
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: platform
subjects:
  - kind: ServiceAccount
    name: gateway-service
roleRef:
  kind: Role
  name: app-discovery
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eureka-discovery
  labels:
    app.kubernetes.io/name: eureka-discovery
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: platform
subjects:
  - kind: ServiceAccount
    name: eureka-server
roleRef:
  kind: Role
  name: app-discovery
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-reader
  labels:
    app.kubernetes.io/name: microservice-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: platform
subjects:
  - kind: ServiceAccount
    name: microservice-default
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io