apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusionauth
  labels:
    app.kubernetes.io/name: fusionauth
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: caicedo-seguros
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
  labels:
    app.kubernetes.io/name: gateway-service
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: caicedo-seguros
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eureka-server
  labels:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: caicedo-seguros
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-default
  labels:
    app.kubernetes.io/name: microservice-default
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: caicedo-seguros
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: application
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: caicedo-seguros
    app.kubernetes.io/managed-by: kustomize
    caicedo.seguros/tier: data
automountServiceAccountToken: false