apiVersion: v1
kind: ConfigMap
metadata:
  name: fusionauth-kickstart
  namespace: develop
  labels:
    app: fusionauth
data:
  kickstart.json: |
    {
      "variables": {
        "defaultTenantId": "d7d09513-a3f5-401c-9685-34ab6c552453",
        "adminEmail": "caicedosegurosaxm@gmail.com",
        "applicationName": "Caicedo Seguros, Consultoria y Servicios S.A.S Portal"
      },
      "apiKeys": [
        {
          "key": "#{FUSIONAUTH_API_KEY}",
          "description": "Core API Key for integrations"
        }
      ],
      "requests": [
        {
          "method": "POST",
          "url": "/api/user/registration",
          "body": {
            "user": {
              "email": "#{adminEmail}",
              "password": "#{FUSIONAUTH_ADMIN_PASSWORD}",
              "firstName": "Admin",
              "lastName": "Caicedo Seguros"
            },
            "registration": {
              "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
              "roles": ["admin", "super-admin"]
            }
          }
        }
      ]
    }