apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

labels:
  - pairs:
      app: fusionauth
      managed-by: kustomize
    includeSelectors: true

resources:
  - deployment.yaml

images:
  - name: fusionauth/fusionauth-app
    newTag: "1.62.1"