apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fusionauth-netpol
  namespace: production
  labels:
    app: fusionauth
spec:
  podSelector:
    matchLabels:
      app: fusionauth

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 9011

    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9011

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgresql
      ports:
        - protocol: TCP
          port: 5432

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 25

    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 443