apiVersion: v1
kind: Service
metadata:
  name: fusionauth-svc
  namespace: production
  labels:
    app: fusionauth
    component: identity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

  selector:
    app: fusionauth
    component: identity

  ports:
    - name: http
      port: 80
      targetPort: 9011
      protocol: TCP
    - name: metrics
      port: 9011
      targetPort: 9011
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: fusionauth-headless
  namespace: production
  labels:
    app: fusionauth
spec:
  clusterIP: None
  selector:
    app: fusionauth
  ports:
    - port: 9011
      name: http