apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusionauth
  namespace: production
  labels:
    app: fusionauth
automountServiceAccountToken: false

---
apiVersion: v1
kind: Secret
metadata:
  name: fusionauth-sa-token
  namespace: production
  annotations:
    kubernetes.io/service-account.name: fusionauth
type: kubernetes.io/service-account-token