apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: eureka-server
      app.kubernetes.io/component: service-discovery
      app.kubernetes.io/part-of: caicedo-seguros
      app.kubernetes.io/managed-by: kustomize