apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eureka-netpol
  labels:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eureka-server
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8761

    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 8761

  egress:
    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eureka-server
      ports:
        - protocol: TCP
          port: 8761