apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - wildcard-production-namespace.yaml
  - wildcard-observability.yaml

labels:
  - pairs:
      caicedo.seguros/environment: production
